### **1. NORMALIZATION PROBLEM**

##### **A randomly generated 5x5 array is required to be normalized for this task. To normalize the random array, first produce it, then center it by subtracting the mean, then scale it by dividing it by the standard deviation. Save the normalized array to a file named `X_normalized.npy}.**

In [18]:
import numpy as np

# Create a 5x5 random values
X = np.random.random((5, 5))

# Calculate the mean and standard deviation
X_mean = np.mean(X)
X_std = np.std(X)

# Standardize the matrix
X_normalized = (X - X_mean) / X_std

# Save the standardized matrix
np.save('X_normalized.npy', X_normalized)

# Load and display the saved data
print("\nOriginal Array:\n", X)
print("\nNormalized Array:\n", X_normalized)




Original Array:
 [[0.57576189 0.00261795 0.59497504 0.81498954 0.62487186]
 [0.45682199 0.98118398 0.07592558 0.49673059 0.29270297]
 [0.433539   0.29508924 0.21695624 0.26992841 0.61749566]
 [0.19926894 0.03431943 0.94627086 0.38320261 0.37182974]
 [0.58350594 0.5705159  0.85258354 0.92892371 0.27469084]]

Normalized Array:
 [[ 0.36081417 -1.70771168  0.43015609  1.22420734  0.53805627]
 [-0.06845016  1.82401738 -1.4431381   0.0755834  -0.66076983]
 [-0.15248051 -0.6521576  -0.93414632 -0.74296519  0.51143492]
 [-0.99798132 -1.59329829  1.69801294 -0.33414884 -0.37519453]
 [ 0.38876312  0.34188094  1.35988735  1.63540559 -0.72577717]]


### **2. DIVISIBLE BY 3 PROBLEM**

##### **The task is to create a 10x10 array containing the squares of the initial 100 positive integers. Finding every element in the array divisible by three is the aim, and the elements saved in a file named `div_by_3.npy` are the result.**

In [9]:
import numpy as np

# Generate random positive integer from 1 to 100
squares = np.arange(1, 101)**2

# Reshape into a 10x10 matrix
squares_10x10 = squares.reshape(10, 10)

# Extract elements divisible by 3
div_by_3 = squares_10x10[squares_10x10 % 3 == 0]

# Save the result to a file
np.save('div_by_3.npy', div_by_3)

# Load and display the saved data
data = np.load('div_by_3.npy')
data


array([   9,   36,   81,  144,  225,  324,  441,  576,  729,  900, 1089,
       1296, 1521, 1764, 2025, 2304, 2601, 2916, 3249, 3600, 3969, 4356,
       4761, 5184, 5625, 6084, 6561, 7056, 7569, 8100, 8649, 9216, 9801])