### **NORMALIZATION PROBLEM**

In [7]:
import numpy as np

# Create a 5x5 matrix of random values
X = np.random.random((5, 5))

# Calculate the mean and standard deviation
X_mean = np.mean(X)
X_std = np.std(X)

# Standardize the matrix
X_normalized = (X - X_mean) / X_std

# Save the standardized matrix
np.save('X_normalized.npy', X_normalized)

# Load and display the saved data
data = np.load('X_normalized.npy')
print(data)


[[ 0.65483425 -1.49893784 -0.93202739  0.73598068  1.70749258]
 [ 0.79066213  0.00586273 -0.8009449  -0.79782179  2.23345644]
 [-0.62457701  0.79004156 -0.74819116 -1.55311414  1.29291191]
 [-0.42321663  0.98098397  0.59103498  0.07546053  0.46433612]
 [-0.5674318  -1.0823687  -0.407538    0.47421195 -1.36110048]]


### **Divisible By 3 Problem**

In [9]:
import numpy as np

# Generate squares of numbers from 1 to 100
squares = np.arange(1, 101)**2

# Reshape into a 10x10 matrix
squares_10x10 = squares.reshape(10, 10)

# Extract elements divisible by 3
div_by_3 = squares_10x10[squares_10x10 % 3 == 0]

# Save the result to a file
np.save('div_by_3.npy', div_by_3)

# Load and display the saved data
data = np.load('div_by_3.npy')
data


array([   9,   36,   81,  144,  225,  324,  441,  576,  729,  900, 1089,
       1296, 1521, 1764, 2025, 2304, 2601, 2916, 3249, 3600, 3969, 4356,
       4761, 5184, 5625, 6084, 6561, 7056, 7569, 8100, 8649, 9216, 9801])